// src/constants/quoteConstants.ts

export const SECCIONES_POR_INCOTERM: Record<string, string[]> = {
  'EXW': ['FLETE INTERNACIONAL', 'FLETE INTERNACIONAL AÉREO', 'Gastos EXW/FCA - FOB', 'GASTOS LOCALES BUENOS AIRES', 'GASTOS LOCALES AGENCIA', 'GASTOS DE AEROPUERTO', 'DERECHOS ADUANEROS (BASIS: CIF VALUE)', 'IMPUESTOS (BASIS: CIF VALUE + DERECHOS ADUANEROS)', 'GASTOS DESPACHO DE ADUANA', 'DELIVERY CHARGES'],
  'FCA': ['FLETE INTERNACIONAL', 'FLETE INTERNACIONAL AÉREO', 'Gastos EXW/FCA - FOB', 'GASTOS LOCALES BUENOS AIRES', 'GASTOS LOCALES AGENCIA', 'GASTOS DE AEROPUERTO', 'GASTOS DE TERMINAL PORTUARIA', 'GASTOS DESPACHO DE ADUANA', 'DELIVERY CHARGES'],
  'FAS': ['FLETE INTERNACIONAL', 'Gastos EXW/FCA - FOB', 'GASTOS LOCALES BUENOS AIRES', 'GASTOS LOCALES AGENCIA', 'DELIVERY CHARGES'],
  'FOB': ['FLETE INTERNACIONAL', 'FLETE INTERNACIONAL AÉREO', 'GASTOS LOCALES BUENOS AIRES', 'GASTOS LOCALES AEREOS', 'DELIVERY CHARGES'],
  'CFR': ['FLETE INTERNACIONAL', 'FLETE INTERNACIONAL AÉREO', 'GASTOS LOCALES BUENOS AIRES', 'GASTOS LOCALES AEREOS', 'DELIVERY CHARGES'],
  'CIF': ['FLETE INTERNACIONAL', 'FLETE INTERNACIONAL AÉREO', 'GASTOS LOCALES BUENOS AIRES', 'GASTOS LOCALES AEREOS', 'DELIVERY CHARGES'],
  'CPT': ['FLETE INTERNACIONAL', 'FLETE INTERNACIONAL AÉREO', 'GASTOS LOCALES BUENOS AIRES', 'GASTOS LOCALES AEREOS', 'DELIVERY CHARGES'],
  'CIP': ['FLETE INTERNACIONAL', 'FLETE INTERNACIONAL AÉREO', 'GASTOS LOCALES BUENOS AIRES', 'GASTOS LOCALES AEREOS', 'DELIVERY CHARGES'],
  'DAP': ['FLETE INTERNACIONAL', 'GASTOS LOCALES BUENOS AIRES', 'GASTOS LOCALES AEREOS', 'DELIVERY CHARGES'],
  'DPU': ['FLETE INTERNACIONAL', 'GASTOS LOCALES BUENOS AIRES', 'GASTOS LOCALES AGENCIA', 'GASTOS LOCALES AEREOS', 'GASTOS DESPACHO DE ADUANA', 'DELIVERY CHARGES'],
  'DDP': ['FLETE INTERNACIONAL', 'GASTOS LOCALES BUENOS AIRES', 'GASTOS LOCALES AGENCIA', 'GASTOS LOCALES AEREOS', 'DERECHOS ADUANEROS (BASIS: CIF VALUE)', 'IMPUESTOS (BASIS: CIF VALUE + DERECHOS ADUANEROS)', 'GASTOS DESPACHO DE ADUANA', 'DELIVERY CHARGES']
};

export const SECCIONES_POR_OPERACION: Record<string, string[]> = {
  'IM': [
    'FLETE INTERNACIONAL',
    'Gastos EXW/FCA - FOB',
    'GASTOS LOCALES BUENOS AIRES',
    'GASTOS LOCALES AGENCIA',
    'DERECHOS ADUANEROS (BASIS: CIF VALUE)',
    'IMPUESTOS (BASIS: CIF VALUE + DERECHOS ADUANEROS)',
    'GASTOS DESPACHO DE ADUANA',
    'GASTOS DE TERMINAL PORTUARIA',
    'DELIVERY CHARGES',
    'SEGURO INTERNACIONAL'
  ],
  'EM': [
    'FLETE INTERNACIONAL',
    'Gastos EXW/FCA - FOB',
    'GASTOS LOCALES BUENOS AIRES',
    'GASTOS LOCALES AGENCIA',
    'DERECHOS ADUANEROS (BASIS: CIF VALUE)',
    'IMPUESTOS (BASIS: CIF VALUE + DERECHOS ADUANEROS)',
    'GASTOS DESPACHO DE ADUANA',
    'GASTOS DE TERMINAL PORTUARIA',
    'DELIVERY CHARGES',
    'SEGURO INTERNACIONAL'
  ],
  'IA': [
    'FLETE INTERNACIONAL AÉREO',
    'Gastos EXW/FCA - FOB',
    'GASTOS LOCALES AEREOS',
    'GASTOS LOCALES AGENCIA',
    'DERECHOS ADUANEROS (BASIS: CIF VALUE)',
    'IMPUESTOS (BASIS: CIF VALUE + DERECHOS ADUANEROS)',
    'GASTOS DESPACHO DE ADUANA',
    'GASTOS DE AEROPUERTO',
    'DELIVERY CHARGES',
    'SEGURO INTERNACIONAL'
  ],
  'EA': [
    'FLETE INTERNACIONAL AÉREO',
    'Gastos EXW/FCA - FOB',
    'GASTOS LOCALES AEREOS',
    'GASTOS LOCALES AGENCIA',
    'DERECHOS ADUANEROS (BASIS: CIF VALUE)',
    'IMPUESTOS (BASIS: CIF VALUE + DERECHOS ADUANEROS)',
    'GASTOS DESPACHO DE ADUANA',
    'GASTOS DE AEROPUERTO',
    'DELIVERY CHARGES',
    'SEGURO INTERNACIONAL'
  ],
  'CO': [
    'FLETE INTERNACIONAL AÉREO',
    'GASTOS LOCALES AGENCIA',
    'DELIVERY CHARGES',
    'SEGURO INTERNACIONAL'
  ],
};

export const CONCEPTOS_POR_SECCION: Record<string, string[]> = {
  'FLETE INTERNACIONAL': ['FLETE INTERNACIONAL Marítimo (CONTENEDOR)', 'FLETE INTERNACIONAL Marítimo (W/M)', 'Bunker Adjustment Factor (BAF)', 'Currency Adjustment Factor (CAF)'],
  'FLETE INTERNACIONAL AÉREO': ['FLETE INTERNACIONAL Aéreo (por Cargable)', 'Fuel Surcharge', 'Security Surcharge', 'Almacenaje (por Peso Real)'],
  'Gastos EXW/FCA - FOB': [
    'Carga en Origen',
    'Documentación de Exportación',
    'Transporte Terrestre Origen',
    'Carga en Origen (por TN)',
    'Carga en Origen (por CBM)',
    'Almacenaje (por TN)',
    'THC (por CBM)'
  ],
  'GASTOS LOCALES BUENOS AIRES': [
    'THC (Terminal Handling Charge)',
    'Toll Fee',
    'Gate Fee',
    'Delivery Order',
    'Desconsolidacion (W/M)',
    'Handling LCL (W/M)',
    'AGP (por TN)'
  ],
  'GASTOS LOCALES AEREOS': [
    'Manejo de Guia',
    'Manejo Local (kilo cobrable)',
    'IATA Fee (% sobre Flete+EXW/FCA-FOB)',
  ],
  'GASTOS LOCALES AGENCIA': ['Agencia Marítima', 'Handling Fee', 'Logistic Fee'],
  'SEGURO INTERNACIONAL': ['Prima de Seguro Internacional'],
  'DERECHOS ADUANEROS (BASIS: CIF VALUE)': ['Derechos de Importación', 'Tasa Estadística'],
  'IMPUESTOS (BASIS: CIF VALUE + DERECHOS ADUANEROS)': ['IVA', 'Tasa de Sellos'],
  'GASTOS DESPACHO DE ADUANA': ['Despacho de Aduana', 'Tramitación Documental'],
  'GASTOS DE TERMINAL PORTUARIA': ['Estadía de Contenedor', 'Manipulación Portuaria'],
  'GASTOS DE AEROPUERTO': ['Tasa de Aeropuerto', 'Manipulación Aérea'],
  'DELIVERY CHARGES': ['Transporte a Destino', 'Descarga en Destino']
};

// Tipos de operación para validación
export const OPERACION_TIPOS = {
  MARITIMO: ['IM', 'EM'],
  AEREO: ['IA', 'EA'],
  TERRESTRE: ['IT', 'ET'],
  CONSOLIDACION: ['CO'],
  COURIER: ['CR']
};

// Tipos de carga
export const TIPO_CARGA = {
  CONTENEDOR: 'CONTENEDOR',
  LCL: 'LCL',
  AEREO: 'AEREO',
  TERRESTRE: 'TERRESTRE'
};